### ISSUE TITLE
Web UI Refresh

### ISSUE THREAD

**Issue by mikhael28** [pareto-learning/fullstackapprenticeship#121]
**Is your feature request related to a problem? Please describe.**
- From a UI perspective, let's refactor the content items. The 'View Content' button is not necessary - we can just make each block a button that's clickable. We can maybe center the text, and make the logo bigger. 
- Adding subcategory header into the subcategory screen, so that people can switch into a different directory

**Additional context*
We want to take a before and after view of the site, to help @pulreq   demonstrate how much he can accomplish in a week's work! I've attached a screenshot here 
<img width="1024" alt="Screen Shot 2019-04-19 at 11 46 47 AM" src="https://user-images.githubusercontent.com/15205259/56441012-5ca33500-62a0-11e9-9247-e1d5c08e4ade.png">

**Comment by scaraclette** [comment]
Want to add description of each item from the directories.js file

**Comment by mikhael28** [comment]
Two things:
1) Following up on @scaraclette 's ticket, we want to add the description of each subcategory from the directories.js file - replace the search bar with that description.
2) We want to, when mapping over the array of objects for the content items, we want to first order the items by their 'priority' or whatever its called attribute. 
3) We want to make the entire card item clickable, and add space below the title for the description.

**Comment by mikhael28** [comment]
The web app is being completely re-written, so I'm closing this!
