### ISSUE TITLE
(1/4) Profile Screen + Forms

### ISSUE THREAD

**Issue by mikhael28** [pareto-learning/fullstackapprenticeship#141]
## Description
We need a Profile Screen for the web that mirrors the functionality of the mobile application screen, and is accessible through the navbar for users that have logged in. It's a mix of Profile and Dashboard screen.

### Screenshots

<img width="293" alt="Screen Shot 2019-05-22 at 3 35 19 PM" src="https://user-images.githubusercontent.com/15205259/58213748-1fb7cd00-7ca8-11e9-90ad-6a10cba02903.png">

### Steps to Reproduce
This functionality appears right when a user logs into the service, right on the home page. 

### Reviewers
N/A

**Comment by mikhael28** [comment]
In order to get the profile information from Mongo, we need to have an actual profile to fetch.

So, we want to create forms (using the same style as the Signup.js and Login.js forms) send a POST request API.post('fsa', '/users', {body})

const body = {
firstName: this.state.firstName,
etc,
}

Reference the ProfileCreation component from the native application to see what fields we need.

For fields like Country, don't worry about integrating some npm module - just make it a straight form. The most important thing is for you to be able to create your account, and then to render the information in the Home.js screen.

**Comment by danluong** [comment]
Change profile submit button to call API post/put depending on this.props.location.state
Change edit profile fields to reflect existing user data
Move fetchProfile functionality into App.js
Remove Profile link on navbar
Rename Profile.js to EditProfile.js

**Comment by mikhael28** [comment]
@danluong you did a great job here! I'm going to be re-writing the web application from scratch, have started a web-series, so I'm going to go ahead and close this! Our open-source work moving forward will be for React-Native components :)
