### ISSUE TITLE
(2/4) Experience System Overview

### ISSUE THREAD

**Issue by mikhael28** [pareto-learning/fullstackapprenticeship#142]
## Description
We want to have a view in the Home/Profile Screen where a User can track their progress through the Apprenticeship/Product Experience system. It would be a button that they could see what % is completed, but would then click into it to see the individual experience items.

### Screenshots

<img width="294" alt="Screen Shot 2019-05-22 at 3 35 33 PM" src="https://user-images.githubusercontent.com/15205259/58213826-69a0b300-7ca8-11e9-9afa-02518e6cac7a.png">
<img width="290" alt="Screen Shot 2019-05-22 at 3 35 43 PM" src="https://user-images.githubusercontent.com/15205259/58213827-69a0b300-7ca8-11e9-8242-addf9d28efcd.png">

### Steps to Reproduce

In order to see this functionality on the web app, on the Home/Dashboard page, we would click into either the Apprenticeship or Portfolio Product card.

### Reviewers
N/A

**Comment by gabrielhug** [comment]
@mikhael28 Requesting assignment for this

**Comment by mikhael28** [comment]
Look into the Thumbnail component in React-Bootstrap

**Comment by gabrielhug** [comment]
Demoing the thumbnail feature in a 'sandbox' route for testing.

**Comment by mikhael28** [comment]
Closing, thanks @gabrielhug
